### ISSUE TITLE
Customized emojis

### ISSUE THREAD

**Issue by Jun711** [danielehrhardt/ionic3-emoji-picker#3]
Hi, 

Thank you for making this plugin! 
I have a question. It seems that these emojis are the default emojis, right? Is it possible to insert non-primitive emojis / images that I made?

**Comment by danielehrhardt** [comment]
Hi @Jun711 

Thank you!!
at the moment we do not Support custom icons because we use the system emojis that is only Unicode not images.


Thank you 
daniel
